### ISSUE TITLE
Allow to connect to servers with self-signed TLS certificates

### ISSUE THREAD

**Issue by HenkKalkwater** [heartfin/harbour-sailfin#17]
Some users use self-signed TLS certificates, which Sailfin simply rejects at the moment. 

I'm thinking of implementing it in the following way:

# Functional requirements:
  * [ ] When a TLS error occurs, prompt to user on what to do. 
  * [ ] Sailfin should remember the user's choice to ignore TLS errors which can be ignored.
  * [ ] For errors about self-signed certificates, Sailfin should ask the user on which certificate to trust and remember it, but it should not automatically trust all self-signed certificates.  

# Implementation steps
* [ ] Listen for the [`QNetworkAccessManager::sslErrors` signal](https://doc.qt.io/archives/qt-5.6/qnetworkaccessmanager.html#sslErrors) and display them properly in the user interface, allowing users to ignore them.
* [ ] [Set the `QNetworkAccessManagerFactory` on the `QQmlEngineInstance`](https://doc.qt.io/archives/qt-5.6/qqmlengine.html#setNetworkAccessManagerFactory) to create a `QNetworkAccessManagers` for the QML side to use, so that the QML part respects the user's choice to ignore TLS warnings as well.
* [ ] Let the media player (gstreamer) respect the ignored TLS errors 
* [ ] Store the TLS errors that the user has ignored and retrieve them later.
